Update Busybox to 1.20.2

diff --git a/user/busybox/scripts/trylink b/user/busybox/scripts/trylink
--- a/user/busybox/scripts/trylink
+++ b/user/busybox/scripts/trylink
@@ -41,9 +41,8 @@ try() {
     printf "%s\n" "$*" >>$EXE.out
     printf "%s\n" "==========" >>$EXE.out
     $debug && echo "Trying: $*"
-    "$@" >>$EXE.out 2>&1
-    exitcode=$?
-    return $exitcode
+    $@ >>$EXE.out 2>&1
+    return $?
 }
 
 check_cc() {
@@ -83,8 +82,34 @@ O_FILES="$5"
 A_FILES="$6"
 LDLIBS="$7"
 
-# The -Wl,--sort-section option is not supported by older versions of ld
-SORT_SECTION=`check_cc "-Wl,--sort-section -Wl,alignment" ""`
+# The --sort-section option is not supported by older versions of ld
+SORT_SECTION=`check_cc "-Wl,--sort-section,alignment" ""`
+
+START_GROUP="-Wl,--start-group"
+END_GROUP="-Wl,--end-group"
+INFO_OPTS="-Wl,--warn-common -Wl,-Map,$EXE.map -Wl,--verbose"
+
+# gold may not support --sort-common (yet)
+SORT_COMMON=`check_cc "-Wl,--sort-common" ""`
+
+# Static linking against glibc produces buggy executables
+# (glibc does not cope well with ld --gc-sections).
+# See sources.redhat.com/bugzilla/show_bug.cgi?id=3400
+# Note that glibc is unsuitable for static linking anyway.
+# We are removing -Wl,--gc-sections from link command line.
+GC_SECTIONS=`(
+. ./.config
+if test x"$CONFIG_STATIC" = x"y"; then
+    check_libc_is_glibc "" "-Wl,--gc-sections"
+else
+    echo "-Wl,--gc-sections"
+fi
+)`
+
+# The --gc-sections option is not supported by older versions of ld
+if test -n "$GC_SECTIONS"; then
+    GC_SECTIONS=`check_cc "$GC_SECTIONS" ""`
+fi
 
 # Sanitize lib list (dups, extra spaces etc)
 LDLIBS=`echo "$LDLIBS" | xargs -n1 | sort | uniq | xargs`
@@ -93,12 +118,13 @@ LDLIBS=`echo "$LDLIBS" | xargs -n1 | sort | uniq | xargs`
 echo "Trying libraries: $LDLIBS"
 # "lib1 lib2 lib3" -> "-llib1 -llib2 -llib3"
 l_list=`echo "$LDLIBS" | sed -e 's/ / -l/g' -e 's/^/-l/' -e 's/^-l$//'`
-test "x$l_list" != "x" && l_list="-Wl,--start-group $l_list -Wl,--end-group"
+test "x$l_list" != "x" && l_list="$START_GROUP $l_list $END_GROUP"
 try $CC $CFLAGS $LDFLAGS \
 	-o $EXE \
-	-Wl,--sort-common \
+	$SORT_COMMON \
 	$SORT_SECTION \
-	-Wl,--start-group $O_FILES $A_FILES -Wl,--end-group \
+	$GC_SECTIONS \
+	$START_GROUP $O_FILES $A_FILES $END_GROUP \
 	$l_list \
 || {
     echo "Failed: $l_list"
@@ -111,49 +137,53 @@ try $CC $CFLAGS $LDFLAGS \
 while test "$LDLIBS"; do
     $debug && echo "Trying libraries: $LDLIBS"
     all_needed=true
+    last_needed=false
     for one in $LDLIBS; do
 	without_one=`echo " $LDLIBS " | sed "s/ $one / /g" | xargs`
 	# "lib1 lib2 lib3" -> "-llib1 -llib2 -llib3"
 	l_list=`echo "$without_one" | sed -e 's/ / -l/g' -e 's/^/-l/' -e 's/^-l$//'`
-	test "x$l_list" != "x" && l_list="-Wl,--start-group $l_list -Wl,--end-group"
+	test x"$l_list" != x"" && l_list="$START_GROUP $l_list $END_GROUP"
 	$debug && echo "Trying -l options: '$l_list'"
 	try $CC $CFLAGS $LDFLAGS \
 		-o $EXE \
-		-Wl,--sort-common \
+		$SORT_COMMON \
 		$SORT_SECTION \
-		-Wl,--start-group $O_FILES $A_FILES -Wl,--end-group \
+		$GC_SECTIONS \
+		$START_GROUP $O_FILES $A_FILES $END_GROUP \
 		$l_list
 	if test $? = 0; then
-	    echo " Library $one is not needed"
+	    echo " Library $one is not needed, excluding it"
 	    LDLIBS="$without_one"
 	    all_needed=false
+	    last_needed=false
 	else
-	    echo " Library $one is needed"
+	    echo " Library $one is needed, can't exclude it (yet)"
+	    last_needed=true
 	fi
     done
     # All libs were needed, can't remove any
     $all_needed && break
-    # If there is no space char, the list has just one lib.
-    # I'm not sure that in this case lib really is 100% needed.
-    # Let's try linking without it anyway... thus commented out.
-    #{ echo "$LDLIBS" | grep -q ' '; } || break
+    # Optimization: was the last tried lib needed?
+    if $last_needed; then
+	# Was it the only one lib left? Don't test again then.
+	{ echo "$LDLIBS" | grep -q ' '; } || break
+    fi
 done
 
 # Make the binary with final, minimal list of libs
 echo "Final link with: ${LDLIBS:-<none>}"
 l_list=`echo "$LDLIBS" | sed -e 's/ / -l/g' -e 's/^/-l/' -e 's/^-l$//'`
-test "x$l_list" != "x" && l_list="-Wl,--start-group $l_list -Wl,--end-group"
+test "x$l_list" != "x" && l_list="$START_GROUP $l_list $END_GROUP"
 # --verbose gives us gobs of info to stdout (e.g. linker script used)
 if ! test -f busybox_ldscript; then
     try $CC $CFLAGS $LDFLAGS \
 	    -o $EXE \
-	    -Wl,--sort-common \
+	    $SORT_COMMON \
 	    $SORT_SECTION \
-	    -Wl,--start-group $O_FILES $A_FILES -Wl,--end-group \
+	    $GC_SECTIONS \
+	    $START_GROUP $O_FILES $A_FILES $END_GROUP \
 	    $l_list \
-	    -Wl,--warn-common \
-	    -Wl,-Map -Wl,$EXE.map \
-	    -Wl,--verbose \
+	    $INFO_OPTS \
     || {
 	cat $EXE.out
 	exit 1
@@ -168,14 +198,13 @@ else
     # Hmm, "ld --sort-section alignment" should do it too.
     try $CC $CFLAGS $LDFLAGS \
 	    -o $EXE \
-	    -Wl,--sort-common \
+	    $SORT_COMMON \
 	    $SORT_SECTION \
-	    -Wl,-T -Wl,busybox_ldscript \
-	    -Wl,--start-group $O_FILES $A_FILES -Wl,--end-group \
+	    $GC_SECTIONS \
+	    -Wl,-T,busybox_ldscript \
+	    $START_GROUP $O_FILES $A_FILES $END_GROUP \
 	    $l_list \
-	    -Wl,--warn-common \
-	    -Wl,-Map -Wl,$EXE.map \
-	    -Wl,--verbose \
+	    $INFO_OPTS \
     || {
 	cat $EXE.out
 	exit 1
@@ -202,13 +231,11 @@ if test "$CONFIG_BUILD_LIBBUSYBOX" = y; then
 	    -Wl,-z,combreloc \
 	    -Wl,-soname="libbusybox.so.$BB_VER" \
 	    -Wl,--undefined=lbb_main \
-	    -Wl,--sort-common \
+	    $SORT_COMMON \
 	    $SORT_SECTION \
-	    -Wl,--start-group $A_FILES -Wl,--end-group \
+	    $START_GROUP $A_FILES $END_GROUP \
 	    $l_list \
-	    -Wl,--warn-common \
-	    -Wl,-Map -Wl,$EXE.map \
-	    -Wl,--verbose \
+	    $INFO_OPTS \
     || {
 	echo "Linking $EXE failed"
 	cat $EXE.out
@@ -223,13 +250,13 @@ if test "$CONFIG_FEATURE_SHARED_BUSYBOX" = y; then
     EXE="$sharedlib_dir/busybox_unstripped"
     try $CC $CFLAGS $LDFLAGS \
 	    -o $EXE \
-	    -Wl,--sort-common \
+	    $SORT_COMMON \
 	    $SORT_SECTION \
-	    -Wl,--start-group $O_FILES -Wl,--end-group \
+	    $GC_SECTIONS \
+	    $START_GROUP $O_FILES $END_GROUP \
 	    -L"$sharedlib_dir" -lbusybox \
-	    -Wl,--warn-common \
-	    -Wl,-Map -Wl,$EXE.map \
-	    -Wl,--verbose \
+	    $l_list \
+	    $INFO_OPTS \
     || {
 	echo "Linking $EXE failed"
 	cat $EXE.out
@@ -261,8 +288,9 @@ int main(int argc, char **argv)
 	EXE="$sharedlib_dir/$name"
 	try $CC $CFLAGS $LDFLAGS "$sharedlib_dir/applet.c" \
 		-o $EXE \
-		-Wl,--sort-common \
+		$SORT_COMMON \
 		$SORT_SECTION \
+		$GC_SECTIONS \
 		-L"$sharedlib_dir" -lbusybox \
 		-Wl,--warn-common \
 	|| {
